version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print-world:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo test-my-shit-part-2!"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print-world:
          requires:
           - say-hello
