version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print-world:
    docker: 
      - imagljlj;lkjk0
    steps:
      - checkout
      - run: exit 1
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print-world:
          requries:
            - say-hello
