version: 2.1

jobs:

  print-world:
    docker: 
      - imagljlj;lkjk0
    steps:
      - checkout
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail


workflows:
  say-hello-workflow:
    jobs:
      - print-world

